name: mtg_blog
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
  - lib/assets/images/mtg_logo.png
  - lib/assets/images/mtg_icon.png
  - lib/assets/ca/server.crt

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/mtg_icon.png"
  min_sdk_android: 21
