import 'package:flutter/material.dart';

final mainTheme = ThemeData(
  brightness: Brightness.light,
  visualDensity: null,
  primarySwatch: null,
  primaryColor: const Color.fromRGBO(218, 45, 24, 1),
  primaryColorLight: null,
  primaryColorDark: null,
  canvasColor: null,
  shadowColor: null,
  scaffoldBackgroundColor: Colors.white,
  bottomAppBarColor: const Color.fromRGBO(218, 45, 24, 1),
  cardColor: const Color.fromRGBO(247, 247, 247, 1),
  dividerColor: const Color.fromRGBO(203, 203, 203, 1),
  focusColor: null,
  hoverColor: null,
  highlightColor: null,
  splashColor: const Color.fromRGBO(95, 166, 249, 1),
  splashFactory: null,
  selectedRowColor: null,
  unselectedWidgetColor: null,
  disabledColor: null,
  buttonTheme:
      const ButtonThemeData(buttonColor: Color.fromRGBO(218, 45, 24, 1)),
  toggleButtonsTheme: null,
  secondaryHeaderColor: null,
  backgroundColor: Colors.white,
  dialogBackgroundColor: Colors.white,
  indicatorColor: null,
  hintColor: null,
  errorColor: null,
  toggleableActiveColor: null,
  fontFamily: 'Bw Modelica',
  textTheme: null,
  primaryTextTheme: null,
  inputDecorationTheme: null,
  iconTheme: null,
  primaryIconTheme: null,
  sliderTheme: null,
  tabBarTheme: null,
  tooltipTheme: null,
  cardTheme: null,
  chipTheme: null,
  platform: null,
  materialTapTargetSize: null,
  applyElevationOverlayColor: null,
  pageTransitionsTheme: null,
  appBarTheme: null,
  scrollbarTheme: null,
  bottomAppBarTheme: null,
  colorScheme: const ColorScheme(
    primary: Color.fromRGBO(238, 177, 32, 1),
    secondary: Color.fromRGBO(208, 31, 42, 1),
    surface: Colors.grey,
    background: Colors.white,
    error: Colors.red,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.grey,
    onBackground: Colors.white,
    onError: Colors.red,
    brightness: Brightness.light,
  ),
  dialogTheme: null,
  floatingActionButtonTheme: null,
  navigationRailTheme: null,
  typography: null,
  cupertinoOverrideTheme: null,
  snackBarTheme: null,
  bottomSheetTheme: null,
  popupMenuTheme: null,
  bannerTheme: null,
  dividerTheme: null,
  buttonBarTheme: null,
  bottomNavigationBarTheme: null,
  timePickerTheme: null,
  textButtonTheme: null,
  elevatedButtonTheme: null,
  outlinedButtonTheme: null,
  textSelectionTheme: null,
  dataTableTheme: null,
  checkboxTheme: null,
  radioTheme: null,
  switchTheme: null,
  progressIndicatorTheme: null,
);
